services:
    db:
        image: postgres:16
        container_name: buddy_postgres
        restart: always
        environment:
            POSTGRES_DB: buddy_db
            POSTGRES_USER: buddy_user
            POSTGRES_PASSWORD: buddy_pass
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: redis_cache
        ports:
            - "6379:6379"
        restart: always

volumes:
    postgres_data:
