services:
    db:
        image: postgres:16
        container_name: buddy_postgres
        restart: always
        environment:
            POSTGRES_DB: buddy_db
            POSTGRES_USER: buddy_user
            POSTGRES_PASSWORD: buddy_pass
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: redis_cache
        restart: always

    web:
        build:
            context: ./
        container_name: django_app
        restart: always
        command: gunicorn buddyscript.wsgi:application --bind 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/media
            - /var/www/static/:/var/www/static/
            - /var/certbot/conf:/etc/letsencrypt/:ro

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - static_volume:/app/staticfiles
            - media_volume:/app/media
            - /var/www/static/:/var/www/static/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - /var/certbot/www/:/var/www/certbot/:ro
        depends_on:
            - web

    certbot:
        image: certbot/certbot:latest
        volumes:
            - /var/certbot/conf:/etc/letsencrypt/:rw
            - /var/certbot/www/:/var/www/certbot/:rw
        depends_on:
            - nginx

volumes:
    postgres_data:
    static_volume:
    media_volume:
