# Generated by Django 6.0.5 on 2026-05-13 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post_image_alter_reaction_reaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshTokenRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jti", models.CharField(max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "device_info",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="refresh_token_records",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "refresh_token_records",
            },
        ),
    ]
