# Generated by Django 6.0.5 on 2026-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_image_alter_refreshtokenrecord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
